# Generated by Django 3.1.1 on 2020-09-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
