# Generated by Django 3.1.1 on 2020-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
