# Generated by Django 3.1.1 on 2020-09-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200927_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('private', 'Private'), ('public', 'Public')], default='public', max_length=15),
        ),
    ]
